### ISSUE TITLE
There's already a module published to npm by this name, i've emailed the maintainer to ask this is to track status of that

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-collection-lodash-mixin#1]

**Comment by klaemo** [comment]
That means we should probably publish our first version as `2.0.0`, since people might already depend on that module.

**Comment by HenrikJoreteg** [comment]
agreed, which would be fine. Hopefully @STRML is gracious enough to let us do so :)

**Comment by klaemo** [comment]
yes :) 
Once that's settled, #3 is fixed and we've reached a consensus on #4, I'll publish the first release.

**Comment by HenrikJoreteg** [comment]
Sounds like a plan. We've been wanting to do an official release script, but in the meantime, i use these aliases to handle publishing ampersand (and other modules). Makes sure we also get git tags pushed to github, etc.

```
alias patch='git pull && npm version patch && git push && git push --tags && npm publish --registry https://registry.npmjs.org'
alias minor='git pull && npm version minor && git push && git push --tags && npm publish --registry https://registry.npmjs.org'
alias major='git pull && npm version major && git push && git push --tags && npm publish --registry https://registry.npmjs.org'
```

**Comment by klaemo** [comment]
nice :+1:

**Comment by HenrikJoreteg** [comment]
Ok, @klaemo, got it. @STRML was super awesome and hooked me up, I added you too @klaemo: https://www.npmjs.com/package/ampersand-collection-lodash-mixin

So you should be able to publish now. 

Let's also leave a thank you to @STRML in the readme. 

Something like: "Big thanks to @STRML who generously gave us this module name on npm. If you're interested in his version, It's still there public, you can just keep using version `1.0.2`"

**Comment by klaemo** [comment]
Awesome!
