### ISSUE TITLE
Publish new major version

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-collection-lodash-mixin#12]
I'm almost done publishing new versions for all lodash@4 related modules. I don't have publish rights to this on npm, so I couldn't do this one.

After this, I'll be able to publish `ampersand-rest-collection` and `ampersand-view` and I think it will be done.

@klaemo Can you publish a major version or this or add me on npm? Thanks!

/cc @samhashemi

**Comment by klaemo** [comment]
Thanks for finishing this, @lukekarrys! I published version 3.0.0 and gave you publish access on npm 🎉

**Comment by lukekarrys** [comment]
Thanks @klaemo! Can you try adding me again? Something weird is happening where I show up on https://www.npmjs.com/package/ampersand-collection-lodash-mixin but not in the registry http://registry.npmjs.org/ampersand-collection-lodash-mixin

**Comment by klaemo** [comment]
You managed to publish, right? Is there still a problem? :confused:

**Comment by lukekarrys** [comment]
npm support helped me out. Not sure what the issue was but they readded me to the package and then it worked.
