### ISSUE TITLE
Add basic tests

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-collection-lodash-mixin#3]
We don't need to test the underlying lodash implementations, just that they're getting properly mapped and applied to the models in the collections, so a single call to each one in a test should be sufficient and was unfortunately absent from the current implementation.

**Comment by klaemo** [comment]
yep, seems reasonable.

**Comment by klaemo** [comment]
Are collections supposed to work with models that only have `model.get(key)`, but not `model[key]`?

**Comment by HenrikJoreteg** [comment]
@klaemo I think we should support both if possible. That way you can use collections to store ampersand models, backbone models, or plain objects if you so choose. Ampersand-models/state all have `get` method too, btw.
