### ISSUE TITLE
drop some methods

### ISSUE THREAD

**Issue by klaemo** [AmpersandJS/ampersand-collection-lodash-mixin#4]
I think we can at least drop all the aliases:
- `all`
- `any`
- `contains`
- `detect`
- `foldr`, `foldl`
- `head`
- `inject`
- `select`
- `tail`

I'd keep `each` though. It's nice :) 

What else?

**Comment by HenrikJoreteg** [comment]
That seems reasonable, as a start i'd say we dump anything that isn't named the same as the actual lodash module.

Don't see much use for `toArray` either. 

I don't know, maybe that's all we want to drop? Let's start there and see what it looks like.
