### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by klaemo** [AmpersandJS/ampersand-collection-lodash-mixin#6]
Hey,

I think, I'm ready to release the first version of this module. It's going to be `2.0.0`, because there already existed an `ampersand-collection-lodash-mixin v1.0.x` on npm, which we were allowed to take over. :)

What do potential consumers of this module think? Looking at you AmpersandJS/ampersand-rest-collection#22! ;-)

I noticed that this mixin is bigger (7.5kb gzipped, deduped) than all of underscore (5.7kb gzipped). I don't know if there's anything we can do about that. It probably is less of a problem when it gets combined with other `ampersand-*` modules, that might share some of the lodash methods.

Feedback welcome!

**Comment by latentflip** [comment]
+1 from me

I shouldn't worry about an extra kb, currently anyone using any rest-collection + any of the other stuff isn't going to see _any_ deduplication as they're now going to have lodash _and_ ampersand stuff. And as you say, as soon as you've got overlapping lodash modules the difference is going to disappear. Besides, the benefits of going lodash aren't solely byte shaving, so I think this is totally okay.

**Comment by lukekarrys** [comment]
+1 from me too.

I did some tests [over here with some of the core modules](https://github.com/AmpersandJS/ampersand/issues/111#issuecomment-88636206) and also found a slight increase going from underscore to lodash. It is a very small amount when it comes to building a full application and I agree with @latentflip that byte shaving isnt the only concern here.

**Comment by HenrikJoreteg** [comment]
let's ship this, IMO +1

**Comment by HenrikJoreteg** [comment]
@klaemo you've got access, publish at will. Then you can open a PR to rest-collection

**Comment by klaemo** [comment]
Just published :tada:
